### ISSUE TITLE
Creating attributes outside of __init__

### ISSUE THREAD

**Issue by hardbyte** [n1analytics/clkhash#100]
From #96: 

> I prefer not to create new attributes in methods outside __init__, eg. `randomnames.load_names` creates `self.all_male_first_names` etc. (ie. give them the value None in `__init__`).

**Comment by nbgl** [comment]
I’ve only saw this occur in `randomnames.NameList`. That is fixed in #146. Please let me know if I’ve missed any others.

**Comment by nbgl** [comment]
Closed by #146.
