### ISSUE TITLE
Command Line Tool not fully unit tested

### ISSUE THREAD

**Issue by hardbyte** [n1analytics/clkhash#103]
The `cli.py` file is covered by unit tests - but many of the tests simply run the code and will pass as long as it doesn't crash... clearly we want to test it does the correct thing.

**Comment by wilko77** [comment]
The `cli.py` file is a light command line wrapper with no additional internal logic. 
Before writing a mock for the ES to unit test the cli, I think it would be more fruitful to just integration test the cli against the entity service directly. 
There is not much extra information to gain from writing dedicated unit tests.

**Comment by hardbyte** [comment]
Good point. Done in https://github.com/n1analytics/clkhash/pull/159 and https://github.com/n1analytics/clkhash/pull/161
