### ISSUE TITLE
Command line documentation doesn't include schema

### ISSUE THREAD

**Issue by hardbyte** [n1analytics/clkhash#107]
The docs for the `cli` currently have this section:

<img width="689" alt="cli-schema" src="https://user-images.githubusercontent.com/855189/38712815-619f5c40-3f11-11e8-8c39-01e80b827396.PNG">

I think we should provide a fully working example including the example schema.

Further down we also show an example "yaml schema" which is used by the generated data.

**Comment by wilko77** [comment]
fixed in version 0.11.0
