### ISSUE TITLE
Tests on Pypy3 fail intermittently with BrokenProcessPool error

### ISSUE THREAD

**Issue by nbgl** [n1analytics/clkhash#117]
The main culprit seems to be `test_clk.py`. The process pool that gets broken is in `clk.generate_clks`.

**Comment by nbgl** [comment]
An example: https://travis-ci.org/n1analytics/clkhash/jobs/367471367

**Comment by nbgl** [comment]
I’m having trouble reproducing this on my own machine. Seems likely that this is caused by Travis.

**Comment by wilko77** [comment]
latest pypy release is `the Python3.5 compatible release — PyPy3.5 v5.10.1`
whereas travis installs `[PyPy 5.8.0-beta0 with GCC 6.2.0 20160901]`

**Comment by wilko77** [comment]
I temporarily moved the pypy3 tests to `allowed_failures` until this issue is resolved

**Comment by hardbyte** [comment]
Pypy testing is back after https://github.com/n1analytics/clkhash/pull/193
