### ISSUE TITLE
readthedocs should list docs for each released version

### ISSUE THREAD

**Issue by wilko77** [n1analytics/clkhash#134]
especially as 'latest' point to our integration branch (master), the docs will not necessarily reflect what's in the current release.

**Comment by hardbyte** [comment]
Ok I've enabled versions for the last few releases. If anyone else has an account on https://readthedocs.org I'll add them as a maintainer.

- http://clkhash.readthedocs.io/en/v0.11.0/
- http://clkhash.readthedocs.io/en/v0.10.1/
