### ISSUE TITLE
References don’t work when documentation is viewed in GitHub

### ISSUE THREAD

**Issue by nbgl** [n1analytics/clkhash#135]
<img width="1018" src="https://user-images.githubusercontent.com/12507513/39160023-608b27aa-47ac-11e8-8d0d-6c8f4da375da.png">
<img width="926" src="https://user-images.githubusercontent.com/12507513/39160022-6062dd86-47ac-11e8-9079-0314dd53ba40.png">
<img width="948" src="https://user-images.githubusercontent.com/12507513/39160021-603b354c-47ac-11e8-8870-9bd3d8746099.png">

Options:

1. Fix this. (There might also not be a fix.)
2. Do nothing. In this case, we need to clearly point everyone to the [hosted documentation](http://clkhash.readthedocs.io/en/stable/) that actually works.

**Comment by wilko77** [comment]
This is not a bug. Github shows source files. The doc has to be compiled with sphinx to resolve references. 
We point to the nicely compiled, readily hosted documentation on readthedocs in the readme. 
Thus it is shown on the landing page for clkhash on github.
