### ISSUE TITLE
SSL failing in Entity Service client tests

### ISSUE THREAD

**Issue by nbgl** [n1analytics/clkhash#238]
From Jenkins in #237:
```
SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)
```

**Comment by hardbyte** [comment]
On it. Root cause was I'd removed the deployment of the `testing.es.data61.xyz` not realizing we relied on it for clkhash cli testing.

**Comment by hardbyte** [comment]
Redeployed and retested.
