### ISSUE TITLE
Mistake in tutorial - examples have one key

### ISSUE THREAD

**Issue by hardbyte** [n1analytics/clkhash#240]
https://clkhash.readthedocs.io/en/latest/tutorial_api.html

**Comment by wilko77** [comment]
That is not a mistake. 
The schema implicitly sets the Blake hashing scheme for all features. The Blake scheme only requires one secret key.
However, I agree that it is somewhat confusing that we have to provide just one key for one scheme and then two keys for the other schemes. Maybe we should prioritize issue #78 to unify the user experience.
Also, we test the tutorial notebooks now. The CI would pick up on mistakes that leads to an exception.
