### ISSUE TITLE
Consider supporting XOR-Folding

### ISSUE THREAD

**Issue by hardbyte** [n1analytics/clkhash#32]
Look into supporting [XOR-Folding for hardening Bloom Filter based Encryptions for PPRL](http://soz-159.uni-duisburg.de/-download=wp-grlc-2016-03.pdf)

**Comment by nbgl** [comment]
Made a new branch for this feature with commit f89aa06.

**Comment by nbgl** [comment]
Implemented in 18e2465. Needs more testing and documentation.

The option is provided as a function argument in the API and a command line argument in the CLI. This should probably be folded into the schema.

**Comment by nbgl** [comment]
This was done in #42.
