### ISSUE TITLE
Standardizing the length of identifiers

### ISSUE THREAD

**Issue by wilko77** [n1analytics/clkhash#41]
From *Privacy-preserving record linkage* by Rainer Schnell:
> The distributions of quasi‐identifiers such as names are usually not uniform, but show high variations and skewness. For example, in a large German administrative database covering about 40% of the population, the length of first names varies between 2 and 24 with a mean of 9.7 (and a skewness of 0.52); the length of last names varies between 2 and 46 with a mean of 7.2 (skewness 1.9). Very long or very short names can be easily identified in a Bloom filter, since the number of bits set to one is exceptionally large or small. Therefore, to protect against this way of re‐identification, the length of identifiers should be standard- ised. Long names could be shortened by deletion or sampling of q‐grams. Shortening the identifiers will prevent the identification of longer names. Furthermore, the distribution of bigram frequencies will change. Short identifiers may be extended by key stretching (Kelsey et al., 1998).

This is a very good point. Mirroring the length distribution of the inputs in the resulting Bloom filters is a bad idea, as it gives the attacker an advantage on matching input to corresponding Bloom filter.

Aha! Link: https://csiro.aha.io/features/ANONLINK-51

**Comment by wilko77** [comment]
Here's a different approach to address this vulnerability:

Instead of controlling the length of the inputs, we control the length of the output.
More precisely, for each identifier, instead of having a fixed _k_ which defines the number of hash functions per n-gram,
we have a parameter _k'_ which defines the total number of hash functions per *input*.
This means, that for different length inputs, we will end up with different _k_ for the corresponding n-grams.
#### Example:
Let's say we want to generate 100 (=_k'_) indices for each first name. Then for "Nico", we hash each of the five bi-grams 20 (=_k_) times, the ten bi-grams of "Inocencia" will be hashed 10 (=_k_) times each.

**Comment by hardbyte** [comment]
I think we can now close this @wilko77 ?
