### ISSUE TITLE
implement schema support

### ISSUE THREAD

**Issue by wilko77** [n1analytics/clkhash#43]

**Comment by nbgl** [comment]
*My plan:*
- Validate schema with jsonschema. This way we know that all the information we expect is there.
- Implement a class for each field type (string/integer/date/enum) with one object per column. Each:
    1. Stores the properties for the field,
    2. Can validate a string passed to it, and
    3. Produces a dictionary of properties for the tokeniser and hasher to use.

The advantage of this approach is extendibility and modularity. We can easily add field types that are all forced to implement the same interface. The parsing of a dictionary of field properties is implemented by one object.

We still get a separation of concerns as the field object simply issues instructions to the tokeniser and the hasher, without tokenising and hashing itself.

*Problems:*
Many default values are included in the JSON master schema. I'd like to find a way to read the schema such that missing values are pre-filled with defaults from the master schema.

Currently, I've been doing this by including the defaults as constants in the code. This is not ideal, as it can cause the Python code to become out of sync with the master schema.

**Comment by nbgl** [comment]
See pull request #69.

**Comment by hardbyte** [comment]
Schema support is now in master. 🎉
