### ISSUE TITLE
CLK statistics

### ISSUE THREAD

**Issue by hardbyte** [n1analytics/clkhash#55]
While processing or as a separate command it would be good to process the hashed clks and output information about the distribution of popcounts.

For example a poorly configured clkhash schema (high `k`, many features) can result in all hashes being mostly `1`s. It would be straightforward to measure the popcount distribution and output to the user.

The cli could optionally use [bashplotlib](https://github.com/glamp/bashplotlib):
![](https://raw.githubusercontent.com/glamp/bashplotlib/master/examples/img/basichist.png)

**Comment by wilko77** [comment]
In PR #62 I introduced statistical information about the generated clks (mean and standard deviation of the popcounts) in the progress bar. It looks something like this:
```
generating CLKs:  16%|█▌        | 8.00K/50.0K [00:03<00:44, 948clk/s, mean=521, std=34.5]
```
No bashplotlib, though. :(

**Comment by hardbyte** [comment]
I think this would be useful as a standalone command e.g.:

```.bash
clkutil describe clks.json
```

**Comment by neilbacon** [comment]
Done in PR Cli describe #187
