### ISSUE TITLE
`python -m clkhash` not working

### ISSUE THREAD

**Issue by nbgl** [n1analytics/clkhash#67]
It should be enough to rename `cli.py` to `__main__.py`.

**Comment by hardbyte** [comment]
Or we could update the docs to say `python -m clkhash.cli`

**Comment by nbgl** [comment]
As far as I can tell, it is convention that you should be able to run `python -m mymodule` for modules that have a CLI, without having to specify a submodule.

For example, `python -m unittest` gives you the CLI does not specify a submodule. Importing the same module (`import unittest`) doesn’t run the CLI but imports the namespace.

**Comment by hardbyte** [comment]
Good point.
